FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_DOWNLOADS=0

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev


RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

# It is important to use the image that matches the builder, as the path to the
# Python executable must be the same, e.g., using python:3.11-slim-bookworm
# will fail.
FROM python:3.13-slim-bookworm

WORKDIR /app

ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

# Copy the application from the builder
COPY --from=builder --chown=app:app /app /app

WORKDIR /app/cloud
