"""
Django settings for quicksnip project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


load_dotenv()

env = os.environ.get

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


def base_dir_join(*args):
    return os.path.join(BASE_DIR, *args)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SITE_ID = 1

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "corsheaders",
    "drf_yasg",
    "rest_framework",
    "django_celery_beat",
    "cloud.filesystem",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django_permissions_policy.PermissionsPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cloud.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cloud.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),   
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST", "db"),
        "PORT": env("POSTGRES_PORT", "5432"),
        "TEST": {
            "DEPENDENCIES": [],
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework.authentication.SessionAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '100/min'
    }
}

# Swagger settings
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": True,
}

# SSO via Cookies
BASE_DOMAIN = env("BASE_DOMAIN")

# Define the domain for which the session and CSRF cookies are valid.
SESSION_COOKIE_DOMAIN = BASE_DOMAIN
CSRF_COOKIE_DOMAIN = BASE_DOMAIN

# Lax allows the cookie to be sent on safe cross-site requests
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Stores the CSRF token in a cookie (not in sessions) and allows frontend JavaScript to read it for AJAX requests.
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
CSRF_COOKIE_HTTPONLY = False
CSRF_TRUSTED_ORIGINS = []

# Ensures the cookie is sent only over HTTPS.
# Specifies the domains allowed to submit requests with a valid CSRF token.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Stores sessions in Redis cache using the default cache, with a one-week expiration.
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", "redis://redis:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 60*60*24*7,
    }
}

# Specifies which origins are allowed to make cross-origin requests.
# Allows credentials (cookies, auth headers) to be included in CORS requests.
CORS_ALLOWED_ORIGINS = []
CORS_ALLOW_CREDENTIALS = True

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True

# Static
# Static files are served by frontend, keeping minimal support for Django admin
STATIC_URL = "/static/"
STATIC_ROOT = base_dir_join("staticfiles")
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Permissions Policy (disable all)
PERMISSIONS_POLICY = {
    "accelerometer": [],
    "camera": [],
    "display-capture": [],
    "encrypted-media": [],
    "geolocation": [],
    "gyroscope": [],
    "magnetometer": [],
    "microphone": [],
    "midi": [],
    "payment": [],
    "usb": [],
    "xr-spatial-tracking": [],
}

# Enables HTTPS with HSTS (including subdomains and preload), redirects HTTP to HTTPS,
# and sets security headers to prevent MIME sniffing, XSS, and clickjacking.
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_PROXY_SSL_HEADER = None
SECURE_SSL_REDIRECT = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
X_FRAME_OPTIONS = "DENY"

# File upload settings
MAX_FILE_UPLOAD_MB = 50
QUOTA_STORAGE_BYTES_PER_USER = 100 * 1024 * 1024
ALLOWED_FILE_MIME_TYPES = [
    "image/jpeg",
    "image/png",
    "video/mp4",
    "application/pdf",
]

# Celery
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ACKS_LATE = True

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False

CELERY_BROKER_TRANSPORT_OPTIONS = {"confirm_publish": True, "confirm_timeout": 5.0}
CELERY_BROKER_POOL_LIMIT = int(env("CELERY_BROKER_POOL_LIMIT", 1))
CELERY_BROKER_CONNECTION_TIMEOUT = float(env("CELERY_BROKER_CONNECTION_TIMEOUT", 30.0))

CELERY_REDIS_MAX_CONNECTIONS = env("CELERY_WORKER_CONCURRENCY", default=None) or None

CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT = env("CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT", "true")
CELERY_TASK_REJECT_ON_WORKER_LOST = env("CELERY_TASK_REJECT_ON_WORKER_LOST", "false")

CELERY_WORKER_PREFETCH_MULTIPLIER = int(env("CELERY_WORKER_PREFETCH_MULTIPLIER", 1))
CELERY_WORKER_CONCURRENCY = int(env("CELERY_WORKER_CONCURRENCY", default=1)) or None
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(env("CELERY_WORKER_MAX_TASKS_PER_CHILD", 1000))
CELERY_WORKER_SEND_TASK_EVENTS = env("CELERY_WORKER_SEND_TASK_EVENTS", "true")

CELERY_EVENT_QUEUE_EXPIRES = float(env("CELERY_EVENT_QUEUE_EXPIRES", 60.0))
CELERY_EVENT_QUEUE_TTL = float(env("CELERY_EVENT_QUEUE_TTL", 5.0))

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
